version: "3.9"  # Specify Docker Compose file version

services:
  app:
    build: .
      
    image: ductrandev99/pop4u-backend
    
    ports:
      - "8000:8000"  # Map port 8000 of the container to port 8000 on the host
    volumes:
      - .:/app  # Mount the current directory as a volume inside the container
    